# Generated by Django 3.1.4 on 2021-01-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCheck',
            fields=[
                ('userID', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('RoomID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
