# Generated by Django 3.1.4 on 2021-01-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210110_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestate',
            name='EMPstate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
